### ISSUE TITLE
Cannot build css

### ISSUE THREAD

**Issue by rabol** [PH7-Jack/livewire-ui#129]
**Describe the bug**
I'm trying to install WireUI in a new Laravel app.

**To Reproduce**
1. create a new laravel app
2. follow the instaruction on how to install WireUI
3. npm run dev

the error:
```
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: require(...) is not a function
    at Object.<anonymous> (/Users/rabol/code/web/test/vendor/ph7jack/wireui/tailwind.config.js:34:34)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/rabol/code/web/test/tailwind.config.js:5:9)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at processResult (/Users/rabol/code/web/test/node_modules/webpack/lib/NormalModule.js:751:19)
    at /Users/rabol/code/web/test/node_modules/webpack/lib/NormalModule.js:853:5
    at /Users/rabol/code/web/test/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/rabol/code/web/test/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/rabol/code/web/test/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/rabol/code/web/test/node_modules/postcss-loader/dist/index.js:142:7)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
```

**Expected behavior**
That the css is build

**Screenshots**
my tailwind.config.js
```
const defaultTheme = require('tailwindcss/defaultTheme');

module.exports = {
    presets: [
        require('./vendor/ph7jack/wireui/tailwind.config.js')
    ],
    purge: {
        enabled: false,
        content: [
            './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
            './vendor/asantibanez/resources/views/*.blade.php',
            './storage/framework/views/*.php',
            './resources/views/**/*.blade.php',
            './vendor/ph7jack/wireui/resources/**/*.blade.php',
            './vendor/ph7jack/wireui/ts/**/*.ts',
            './vendor/ph7jack/wireui/src/View/**/*.php'
        ]
    },

    theme: {
        extend: {
            fontFamily: {
                sans: ['Nunito', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    variants: {
        extend: {
            opacity: ['disabled'],
        },
    },

    plugins: [require('@tailwindcss/forms')],
};
```

my app.css
```
@import 'tailwindcss/base';
@import 'tailwindcss/components';
@import 'tailwindcss/utilities';
```
**Desktop (please complete the following information):**
 - OS: MacOS 11.6.1
- npm: 8.1.0
- node: v17.0.1
- php v 8.0.12

**Comment by ph7jack** [comment]
@rabol Can you show me your laravel mix code?

**Comment by rabol** [comment]
Here it is
````
const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js').postCss('resources/css/app.css', 'public/css', [
    require('postcss-import'),
    require('tailwindcss'),
    require('autoprefixer'),
]);
````

**Comment by rabol** [comment]
I tried to create my own preset file and this seems to work:

```
const colors = require('tailwindcss/colors')

module.exports = {
    purge: {
        content: [
        './vendor/ph7jack/wireui/ts/**/*.js',
        './vendor/ph7jack/wireui/resources/views/**/*.blade.php',
        './vendor/ph7jack/wireui/src/View/**/*.php'
        ],
    },
    theme: {
        extend: {
            colors: {
                blueGray: colors.blueGray,
                primary: colors.indigo,
                secondary: colors.gray,
                positive: colors.emerald,
                negative: colors.red,
                warning: colors.amber,
                info: colors.blue
            },
            fontSize: {
                '2xs': '.5rem'
            },
            spacing: {
                '4.5': '1.13rem'
            }
        }
    },

    plugins: [
        //require('@tailwindcss/forms')({
        //    strategy: 'class',
        //}),
        require('./vendor/ph7jack/wireui/tailwindcss/plugins/hideScrollbar')
    ]
}

```

just need to figure out the th require() does not work

**Comment by rabol** [comment]
By default a new new project created with Laravel installer and Breeze installs v0.2.1 of tailwindcss/forms, but one need ^0.3.0
