### ISSUE TITLE
Tailwind/webpack is not compiling successfully because of the config file

### ISSUE THREAD

**Issue by Reex11** [PH7-Jack/livewire-ui#135]
**Describe the bug**
I faced an error (even though its marked as a warning but I think the compile do break before completion) while compiling with mix.

```
(node:37716) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'version' of undefined    at Object.loader (XXXX\node_modules\postcss-loader\dist\index.js:102:54)(Use `node --trace-warnings ...` to show where the warning was created)(node:37716) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**To Reproduce**

1. here's my `tailwind.config.js` file: (shortcutted)
```
const defaultTheme = require('tailwindcss/defaultTheme');
const colors = require('tailwindcss/colors');

module.exports = {
    mode:'jit',
    presets: [
        require('./vendor/ph7jack/wireui/tailwind.config.js')
    ],
    purge: {
        content: [
            './vendor/livewire-ui/modal/resources/views/*.blade.php',
            './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
            './storage/framework/views/*.php',
            './resources/views/**/*.{js,vue,blade.php}',
            './resources/**/**/*.{js,css}',
            './vendor/ph7jack/wireui/resources/**/*.blade.php',
            './vendor/ph7jack/wireui/ts/**/*.ts',
            './vendor/ph7jack/wireui/src/View/**/*.php'
        ],
        safelist: [
           // hidden content
        ]



    },
    darkMode: 'class', // false, media or class
    theme: {
        extend: {
                    // hidden content
        },
    },

    variants: {
        extend: {
            opacity: ['disabled'],
        },
    },

    plugins: [
        // hidden content
    ],
};
```

2. run `npm run prod` or `npm run dev` or `npm run watch`

**Versions:**
 - npm: 6.14.15
 - node: v14.17.6
 - postcss: 8.3.5
 - postcss loader: 6.1.0
 - postcss import: 12.0.1
 - tailwindcss: 2.2.19

The error is gone once I remove the following from `wireui\tailwind.config.js`
```
    require("@tailwindcss/forms")({
      strategy: 'class',
    }),
```
I've managed to narrow the issue down to this part. `({ strategy: 'class', })` It works fine when I remove it.
.. Its possible that this is a Tailwindcss issue.

As a workaround I removed Wireui's tailwind.config.js from my tailwind config presets.

**Comment by ph7jack** [comment]
Are you using the latest modules version?

**Comment by Reex11** [comment]
I think you mean NPM packages, right?
I updated them and here's a new error 😅 
```
ERROR in ./resources/css/app.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: require(...) is not a function
    at Object.<anonymous> (XXXX\vendor\ph7jack\wireui\tailwind.config.js:34:34)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (XXXX\tailwind.config.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at processResult (XXXX\node_modules\webpack\lib\NormalModule.js:751:19)
    at XXXX\node_modules\webpack\lib\NormalModule.js:853:5
    at XXXX\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at XXXX\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (XXXX\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (XXXX\node_modules\postcss-loader\dist\index.js:142:7)
```

**Comment by ph7jack** [comment]
Yes, the tailwind, postcss, tailwindforms, is all updated?

**Comment by detygon** [comment]
I can confirm this issue, I had to copy the content of the `tailwind.config.js` file and paste it into my own config to update it. I use the latest version of each library. Here the content of my package.json file.
```json
"devDependencies": {
        "@tailwindcss/forms": "^0.3.4",
        "@tailwindcss/typography": "^0.4.1",
        "alpinejs": "^2.8.2",
        "autoprefixer": "^10.4.0",
        "axios": "^0.24.0",
        "laravel-mix": "^6.0.39",
        "lodash": "^4.17.21",
        "postcss": "^8.3.11",
        "postcss-import": "^14.0.2",
        "tailwindcss": "^2.2.19"
    }
```

**Comment by mckenziearts** [comment]
This error it's fix when your update tailwindcss/forms to the latest version `"@tailwindcss/forms": "^0.3.4",`

**Comment by Reex11** [comment]
Thats right! 
@tailwindcss/forms was not updated.

Thank you all 💙
