### ISSUE TITLE
Uncaught TypeError: t.execute is not a function

### ISSUE THREAD

**Issue by gbrits** [PH7-Jack/livewire-ui#307]
Code per the documentation:

```php
$this->dialog([
    'title'       => 'Are you sure?',
    'description' => 'Delete blockout date',
    'icon'        => 'question',
    'accept'      => [
        'label'  => 'Yes, delete it',
        'method' => 'confirmedDeleteBlockout',
    ],
    'reject' => [
        'label'  => 'No, cancel',
    ],
]);
```

...getting the following error when the Dialog attempts to run the method:

```console
Uncaught TypeError: t.execute is not a function
    at Proxy.accept (scripts:1:25698)
    at runIfTypeOfFunction (app.js:1742:24)
    at app.js:1730:9
    at tryCatch (app.js:1655:12)
    at app.js:3398:5
    at handler3 (app.js:2818:25)
    at app.js:2865:5
    at HTMLButtonElement.<anonymous> (app.js:2820:52)
```

**Comment by joelhmetz** [comment]
https://livewire-wireui.com/docs/dialogs

You have to follow the instructions on this page. Send the complete code, not only the part of the call.

**Comment by ph7jack** [comment]
@gbrits are you using it inside a livewire component?

**Comment by gbrits** [comment]
Hi @PH7-Jack - yes that's right. (Btw, it appears in the middle of the screen, not top right like the demos show, despite being latest version)

It should be noted that my async-data x-select is also **half** working -- it draws data from the backend and autocompletes on searching, but the selection process doesn't work. So I think there's something that's off. I am using Jetstream & Livewire & AlpineJS 3. Here are my versions:

`composer.json`:
```json
"require": {
    "php": "^7.3|^8.1",
    "aws/aws-sdk-php": "^3.209",
    "doctrine/dbal": "^3.3",
    "erusev/parsedown": "^1.7",
    "fruitcake/laravel-cors": "^2.0",
    "guzzlehttp/guzzle": "^7.0.1",
    "laravel/framework": "^9.0",
    "laravel/jetstream": "^2.4",
    "laravel/sanctum": "^2.11",
    "laravel/telescope": "^4.9",
    "laravel/tinker": "^2.5",
    "livewire/livewire": "^2.10.5",
    "wireui/wireui": "^1.5"
},
```

`EditEmployee.php` Livewire component:
```php
public function confirmedDeleteBlockout() {
    ContactBlockoutDates::destroy($this->blockout['id']);
    $this->emit('refresh')->to('blockout-table');
    $this->closeBlockoutModal();
    $this->notification()->success(
        $title = 'Deleted',
        $description = 'That blockout date has been removed.'
    );
}

public function deleteBlockoutDate() {
    $this->dialog([
        'title'       => 'Are you sure?',
        'description' => 'Delete blockout date',
        'icon'        => 'question',
        'accept'      => [
            'label'  => 'Yes, delete it',
            'method' => 'confirmedDeleteBlockout'
        ],
        'reject' => [
            'label'  => 'No, cancel',
        ],
    ]);
}
```

`app.blade.php`:
```blade
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="h-full bg-gray-100 scroll-smooth">
<head>
...
    @livewireStyles
...
    <wireui:scripts />
    <script src="{{ mix('js/app.js') }}" defer></script>
...
</head>
<body class="font-sans antialiased h-full">
    <x-notifications />
    <x-dialog z-index="z-50" />
    <x-jet-banner />
  ...
                        {{ $slot }}
 ...
    @livewireScripts
    <script src="https://maps.googleapis.com/maps/api/js?key=(hidden_key)&libraries=places"></script>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{{ asset('js/google-autocomplete.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.10.1/main.min.js" integrity="sha256-TdTSDSjuCyswg+ZC7ekTsOatmHRtTdToHybuyu2TZnY=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar-scheduler@5.10.1/main.min.css" integrity="sha256-RoGeDStTbXClGRj4hllIdGBYrCgEmO7H8SmutsYdDLU=" crossorigin="anonymous">
    <style>
        .fc .fc-toolbar-title {
            font-size: 16px;
            margin: 0;
            font-weight: normal;
            padding: 0;
            margin: 0;
        }
    </style>
    <script src="{{ asset('js/livewire-events.js') }}" async></script>
    <script>
        window.addEventListener("resize", function(){
            if (document.documentElement.clientWidth > 768) {
                Livewire.emit('ensureSidebarClosed')
            }
        }, true);
    </script>
</body>
</html>
```

Finally, my `resources/js/app.js` file:

```javascript
require('./bootstrap');

window.moment = require('moment');
window.Pikaday = require('pikaday');

import Alpine from 'alpinejs';
window.Alpine = Alpine;

window.Wireui.hook('load', () => Alpine.start());
```

`package.json`:
```json
"devDependencies": {
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.4.0",
    "@tailwindcss/line-clamp": "^0.3.1",
    "@tailwindcss/typography": "^0.5.0",
    "alpinejs": "^3.0.6",
    "autoprefixer": "^10.4.2",
    "axios": "^0.21",
    "laravel-echo": "^1.11.7",
    "laravel-mix": "^6.0.41",
    "lodash": "^4.17.19",
    "postcss": "^8.4.5",
    "postcss-import": "^14.0.1",
    "postcss-loader": "^6.2.1",
    "prettier": "2.5.1",
    "pusher-js": "^7.1.0-beta",
    "tailwindcss": "^3.0.15"
},
"dependencies": {
    "@fortawesome/fontawesome-free": "^6.1.1",
    "@fullcalendar/core": "^5.10.1",
    "@fullcalendar/daygrid": "^5.10.1",
    "@fullcalendar/list": "^5.10.1",
    "@fullcalendar/resource-timeline": "^5.10.1",
    "@fullcalendar/timegrid": "^5.10.1",
    "fullcalendar-scheduler": "^5.10.1",
    "moment": "^2.29.3",
    "pikaday": "^1.8.2",
    "toastr": "^2.1.4"
}
```

**Comment by MohmmedAshraf** [comment]
same issue

**Comment by geek-jeef** [comment]
Hello, I have exactly the same problem.

**Comment by ph7jack** [comment]
@geek-jeef @MohmmedAshraf @gbrits 
Sorry, the doc was outdated. I've updated it now.
When you have confirmation buttons, you MUST use the **confirmDialog** instead of the **dialog** method
```
$this->dialog()->confirm([
    'title'       => 'Are you sure?',
    'description' => 'Delete blockout date',
    'icon'        => 'question',
    'accept'      => [
        'label'  => 'Yes, delete it',
        'method' => 'confirmedDeleteBlockout',
    ],
    'reject' => [
        'label'  => 'No, cancel',
    ],
]);
```
