### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by tomhelmer** [PH7-Jack/livewire-ui#363]
Importing javascript with  `<wireui:scripts />` does not work with the new Vite asset bundler.

It's now default for new Laravel projects, so support for this is vital.

**Comment by dominikgeimer** [comment]
I have no problem to use it with Vite.

This is in my layouts.app `<head>`

```
@wireUiScripts
@vite(['resources/css/app.css', 'resources/js/app.js'])
```

**Comment by tomhelmer** [comment]
Hi, thanks for the fast response. 
I accidently re-ordered the imports in my template.
I can confirm it works after importing the wireui scripts first

**Comment by l0gical** [comment]
> I have no problem to use it with Vite.
> 
> This is in my layouts.app `<head>`
> 
> ```
> @wireUiScripts
> @vite(['resources/css/app.css', 'resources/js/app.js'])
> ```

Exactly how I have installed mine

**Comment by hmihail** [comment]
I have the same in my layout file, but I receive a huge number of errors in the console:

module.esm.js:416 Alpine Expression Error: wireui_datetime_picker is not defined

```
Uncaught ReferenceError: wireui_datetime_picker is not defined
    at eval (eval at safeAsyncFunction (module.esm.js:471:14), <anonymous>:3:16)
    at module.esm.js:489:21
    at tryCatch (module.esm.js:409:12)
    at evaluate (module.esm.js:434:31)
    at module.esm.js:2641:15
    at Function.<anonymous> (module.esm.js:1165:55)
    at flushHandlers (module.esm.js:561:45)
    at stopDeferring (module.esm.js:566:5)
    at deferHandlingDirectives (module.esm.js:569:3)
    at initTree (module.esm.js:778:3)
eval @ VM5794:3
(anonymous) @ module.esm.js:489
tryCatch @ module.esm.js:409
evaluate @ module.esm.js:434
(anonymous) @ module.esm.js:2641
(anonymous) @ module.esm.js:1165
flushHandlers @ module.esm.js:561
stopDeferring @ module.esm.js:566
deferHandlingDirectives @ module.esm.js:569
initTree @ module.esm.js:778
(anonymous) @ module.esm.js:738
start @ module.esm.js:737
(anonymous) @ app.js:6
setTimeout (async)
handleError @ module.esm.js:419
(anonymous) @ module.esm.js:489
Promise.catch (async)
(anonymous) @ module.esm.js:489
tryCatch @ module.esm.js:409
evaluate @ module.esm.js:434
(anonymous) @ module.esm.js:2641
(anonymous) @ module.esm.js:1165
flushHandlers @ module.esm.js:561
stopDeferring @ module.esm.js:566
deferHandlingDirectives @ module.esm.js:569
initTree @ module.esm.js:778
(anonymous) @ module.esm.js:738
start @ module.esm.js:737
(anonymous) @ app.js:6
module.esm.js:420 Uncaught ReferenceError: model is not defined
    at eval (eval at safeAsyncFunction (module.esm.js:471:14), <anonymous>:3:32)
    at module.esm.js:489:21
    at tryCatch (module.esm.js:409:12)
    at module.esm.js:2623:17
    at reactiveEffect (module.esm.js:1609:16)
    at Object.effect2 [as effect] (module.esm.js:1584:5)
    at effect (module.esm.js:48:33)
    at wrappedEffect (module.esm.js:64:27)
    at Function.<anonymous> (module.esm.js:2623:3)
    at flushHandlers (module.esm.js:561:45)
eval @ VM5795:3
(anonymous) @ module.esm.js:489
tryCatch @ module.esm.js:409
(anonymous) @ module.esm.js:2623
reactiveEffect @ module.esm.js:1609
effect2 @ module.esm.js:1584
effect @ module.esm.js:48
wrappedEffect @ module.esm.js:64
(anonymous) @ module.esm.js:2623
flushHandlers @ module.esm.js:561
stopDeferring @ module.esm.js:566
deferHandlingDirectives @ module.esm.js:569
initTree @ module.esm.js:778
(anonymous) @ module.esm.js:738
start @ module.esm.js:737
(anonymous) @ app.js:6
setTimeout (async)
handleError @ module.esm.js:419
(anonymous) @ module.esm.js:489
Promise.catch (async)
(anonymous) @ module.esm.js:489
tryCatch @ module.esm.js:409
(anonymous) @ module.esm.js:2623
reactiveEffect @ module.esm.js:1609
effect2 @ module.esm.js:1584
effect @ module.esm.js:48
wrappedEffect @ module.esm.js:64
(anonymous) @ module.esm.js:2623
flushHandlers @ module.esm.js:561
stopDeferring @ module.esm.js:566
deferHandlingDirectives @ module.esm.js:569
initTree @ module.esm.js:778
(anonymous) @ module.esm.js:738
start @ module.esm.js:737
(anonymous) @ app.js:6
module.esm.js:420 Uncaught ReferenceError: model is not defined
    at eval (eval at safeAsyncFunction (module.esm.js:471:14), <anonymous>:3:32)
    at module.esm.js:489:21
    at tryCatch (module.esm.js:409:12)
    at module.esm.js:2692:17
    at reactiveEffect (module.esm.js:1609:16)
    at Object.effect2 [as effect] (module.esm.js:1584:5)
    at effect (module.esm.js:48:33)
    at wrappedEffect (module.esm.js:64:27)
    at Function.<anonymous> (module.esm.js:2692:3)
    at flushHandlers (module.esm.js:561:45)
eval @ VM5797:3
(anonymous) @ module.esm.js:489
tryCatch @ module.esm.js:409
(anonymous) @ module.esm.js:2692
reactiveEffect @ module.esm.js:1609
effect2 @ module.esm.js:1584
effect @ module.esm.js:48
wrappedEffect @ module.esm.js:64
(anonymous) @ module.esm.js:2692
flushHandlers @ module.esm.js:561
stopDeferring @ module.esm.js:566
deferHandlingDirectives @ module.esm.js:569
initTree @ module.esm.js:778
(anonymous) @ module.esm.js:738
start @ module.esm.js:737
(anonymous) @ app.js:6
setTimeout (async)
handleError @ module.esm.js:419
(anonymous) @ module.esm.js:489
Promise.catch (async)
(anonymous) @ module.esm.js:489
tryCatch @ module.esm.js:409
(anonymous) @ module.esm.js:2692
reactiveEffect @ module.esm.js:1609
effect2 @ module.esm.js:1584
effect @ module.esm.js:48
wrappedEffect @ module.esm.js:64
(anonymous) @ module.esm.js:2692
flushHandlers @ module.esm.js:561
stopDeferring @ module.esm.js:566
deferHandlingDirectives @ module.esm.js:569
initTree @ module.esm.js:778
(anonymous) @ module.esm.js:738
start @ module.esm.js:737
(anonymous) @ app.js:6
module.esm.js:420 Uncaught ReferenceError: position is not defined
    at eval (eval at safeAsyncFunction (module.esm.js:471:14), <anonymous>:4:22)
    at module.esm.js:489:21
    at tryCatch (module.esm.js:409:12)
    at module.esm.js:2623:17
    at reactiveEffect (module.esm.js:1609:16)
    at Object.effect2 [as effect] (module.esm.js:1584:5)
    at effect (module.esm.js:48:33)
    at wrappedEffect (module.esm.js:64:27)
    at Function.<anonymous> (module.esm.js:2623:3)
    at flushHandlers (module.esm.js:561:45)
```

... and it continues ....

Any suggestions?
Thanks!
